name: Build Image
description: Build a container image with Workflow Engine
inputs:
  args:
    description: Comma seperated list of build time variables
  artifact_dir:
    description: The target directory for all generated artifacts
    default: artifacts
  build_dir:
    description: The build directory to using during an image build
    default: .
  cache_from:
    description: External cache sources (e.g., "user/app:cache", "type=local,src=path/to/dir")
  cache_to:
    description: Cache export destinations (e.g., "user/app:cache", "type=local,src=path/to/dir")
  config_file:
    description: The workflow engine config file name
  dockerfile:
    description: The Dockerfile/Containerfile to use during an image build
    default: Dockerfile
  gatecheck_bundle_filename:
    description: The filename for the gatecheck bundle, a validatable archive of security artifacts
    default: gatecheck-bundle.tar.gz
  image_tag:
    description: The full image tag for the target container image
    default: my-app:latest
  platform:
    description: The target platform for build
  squash_layers:
    description: squash image layers - Only Supported with Podman CLI
  target:
    description: The target build stage to build (e.g., [linux/amd64])
runs:
  using: docker
  image: ghcr.io/cms-enterprise/batcave/workflow-engine:v0.0.1-rc.11
  args: [run, image-build, --cli-interface, docker, --config, '${{ inputs.config_file }}', --verbose]
  env:
    WFE_ARTIFACT_DIR: ${{ inputs.artifact_dir }}
    WFE_GATECHECK_BUNDLE_FILENAME: ${{ inputs.gatecheck_bundle_filename }}
    WFE_IMAGE_BUILD_ARGS: ${{ inputs.args }}
    WFE_IMAGE_BUILD_CACHE_FROM: ${{ inputs.cache_from }}
    WFE_IMAGE_BUILD_CACHE_TO: ${{ inputs.cache_to }}
    WFE_IMAGE_BUILD_DIR: ${{ inputs.build_dir }}
    WFE_IMAGE_BUILD_DOCKERFILE: ${{ inputs.dockerfile }}
    WFE_IMAGE_BUILD_PLATFORM: ${{ inputs.platform }}
    WFE_IMAGE_BUILD_SQUASH_LAYERS: ${{ inputs.squash_layers }}
    WFE_IMAGE_BUILD_TARGET: ${{ inputs.target }}
    WFE_IMAGE_TAG: ${{ inputs.image_tag }}
