name: Build Image Podman
description: Builds a Container Image using workflow-engine

inputs:
  config_file:
    description: "The file location where the workflow-engine configuration is located"
    default: ""
  build_dir:
    description: "The directory where the image build takes place."
  dockerfile:
    description: "The name/path of the Dockerfile."
  tag:
    description: "The tag to be applied to the built image."
  platform:
    description: "The platform for the image build."
  target:
    description: "The target build stage in the Dockerfile."
  cache_to:
    description: "Specifies where to store build cache."
  cache_from:
    description: "Specifies where to load build cache from."

runs:
  using: docker
  image: "docker://ghcr.io/cms-enterprise/batcave/workflow-engine:podman-v0.0.1-rc.7"
  args: [ "run", "image-build", "--config", "${{inputs.config_file}}", "-i", "podman" ]
  env:
    WFE_IMAGE_BUILD_DIR: "${{inputs.build_dir}}"
    WFE_IMAGE_BUILD_DOCKERFILE: "${{inputs.dockerfile}}"
    WFE_IMAGE_TAG: "${{inputs.tag}}"
    WFE_BUILD_IMAGE_PLATFORM: "${{inputs.platform}}"
    WFE_IMAGE_BUILD_TARGET: "${{inputs.target}}"
    WFE_IMAGE_BUILD_CACHE_TO: "${{inputs.cache_to}}"
    WFE_IMAGE_BUILD_CACHE_FROM: "${{inputs.cache_from}}"
    WFE_IMAGE_BUILD_SCAN_TARGET: "${{inputs.scan_target}}"
