name: Code Scan
description: Scans code using workflow-engine

inputs:
  config_file:
    description: The file location where the workflow-engine configuration is located
    default: ""
  args:
    description: optional build arguments for the code scan. Should be passed as comma seperated env values like "key1=value1,key2=value2"

runs:
  using: docker
  image: "docker://ghcr.io/cms-enterprise/batcave/workflow-engine:v0.0.1-rc.9"
  args: [ "run", "code-scan", "--config", "${{inputs.config_file}}", "--verbose" ]
  env:
    WFE_CODE_SCAN_ARGS: "${{ inputs.args }}"
