name: Code Scan
description: Scan a code repository with Workflow Engine
inputs:
  artifact_dir:
    description: The target directory for all generated artifacts
    default: artifacts
  config_file:
    description: The workflow engine config file name
  gatecheck_bundle_filename:
    description: The filename for the gatecheck bundle, a validatable archive of security artifacts
    default: gatecheck-bundle.tar.gz
  gitleaks_filename:
    description: The filename for the gitleaks secret report - must contain 'gitleaks'
    default: gitleaks-secrets-report.json
  gitleaks_src_dir:
    description: The target directory for the gitleaks scan
    default: .
  semgrep_filename:
    description: The filename for the semgrep SAST report - must contain 'semgrep'
    default: semgrep-sast-report.json
  semgrep_rules:
    description: Semgrep ruleset manual override
    default: p/default
runs:
  using: docker
  image: ghcr.io/cms-enterprise/batcave/workflow-engine:v0.0.1-rc.11
  args: [run, code-scan, --config, '${{ inputs.config_file }}', --verbose]
  env:
    WFE_ARTIFACT_DIR: ${{ inputs.artifact_dir }}
    WFE_CODE_SCAN_GITLEAKS_FILENAME: ${{ inputs.gitleaks_filename }}
    WFE_CODE_SCAN_GITLEAKS_SRC_DIR: ${{ inputs.gitleaks_src_dir }}
    WFE_CODE_SCAN_SEMGREP_FILENAME: ${{ inputs.semgrep_filename }}
    WFE_CODE_SCAN_SEMGREP_RULES: ${{ inputs.semgrep_rules }}
    WFE_GATECHECK_BUNDLE_FILENAME: ${{ inputs.gatecheck_bundle_filename }}
