name: Image Scan
description: Scan a container image with Workflow Engine
inputs:
  artifact_dir:
    description: The target directory for all generated artifacts
    default: artifacts
  clamav_filename:
    description: The filename for the clamscan virus report - must contain 'clamav'
    default: clamav-virus-report.txt
  config_file:
    description: The workflow engine config file name
  gatecheck_bundle_filename:
    description: The filename for the gatecheck bundle, a validatable archive of security artifacts
    default: gatecheck-bundle.tar.gz
  grype_config_filename:
    description: The config filename for the grype vulnerability report
  grype_filename:
    description: The filename for the grype vulnerability report - must contain 'grype'
    default: grype-vulnerability-report-full.json
  image_tag:
    description: The full image tag for the target container image
    default: my-app:latest
  syft_filename:
    description: The filename for the syft SBOM report - must contain 'syft'
    default: syft-sbom-report.json
runs:
  using: docker
  image: ghcr.io/cms-enterprise/batcave/workflow-engine:podman-v0.0.1-rc.11
  args: [run, image-scan, --cli-interface, podman, --config, '${{ inputs.config_file }}', --verbose]
  env:
    WFE_ARTIFACT_DIR: ${{ inputs.artifact_dir }}
    WFE_GATECHECK_BUNDLE_FILENAME: ${{ inputs.gatecheck_bundle_filename }}
    WFE_IMAGE_SCAN_CLAMAV_FILENAME: ${{ inputs.clamav_filename }}
    WFE_IMAGE_SCAN_GRYPE_CONFIG_FILENAME: ${{ inputs.grype_config_filename }}
    WFE_IMAGE_SCAN_GRYPE_FILENAME: ${{ inputs.grype_filename }}
    WFE_IMAGE_SCAN_SYFT_FILENAME: ${{ inputs.syft_filename }}
    WFE_IMAGE_TAG: ${{ inputs.image_tag }}
