name: Scan Image Podman
description: Scans a Container Image using workflow-engine

inputs:
  config_file:
    description: "The file location where the workflow-engine configuration is located"
    default: ""
  tag:
    description: "The target for image scanning."
  clamav_filename:
    description: "Filename for ClamAV scan report."
  syft_filename:
    description: "Filename for Syft SBOM report."
  grype_config_filename:
    description: "Configuration file for Grype."
  grype_active_findings_filename:
    description: "Filename for Grype active findings report."
  grype_all_findings_filename:
    description: "Filename for Grype full findings report."
  artifact_dir:
    description: "The directory where image scan artifacts should be stored"

runs:
  using: docker
  image: "docker://ghcr.io/cms-enterprise/batcave/workflow-engine:podman-56dca66a"
  args: [ "run", "image-scan", "--config", "${{inputs.config_file}}", "-i", "podman" ]
  env:
    WFE_IMAGE_TAG: "${{inputs.tag}}"
    WFE_IMAGE_SCAN_CLAMAV_FILENAME: "${{inputs.clamav_filename}}"
    WFE_IMAGE_SCAN_SYFT_FILENAME: "${{inputs.syft_filename}}"
    WFE_IMAGE_SCAN_GRYPE_CONFIG_FILENAME: "${{inputs.grype_config_filename}}"
    WFE_IMAGE_SCAN_GRYPE_ACTIVE_FINDINGS_FILENAME: "${{inputs.grype_active_findings_filename}}"
    WFE_IMAGE_SCAN_GRYPE_ALL_FINDINGS_FILENAME: "${{inputs.grype_all_findings_filename}}"
    WFE_ARTIFACT_DIR: "${{inputs.artifact_dir}}"
