name: Build workflow-engine
run-name: "Building workflow-engine Image: ${{ github.event.head_commit.message }}"
on:
  push:
    branches:
      - main
      - feat/*
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # In order to support caching we need to make sure we are using the docker-container driver for builds
      # - name: Restore image layer cache
      #   uses: actions/cache/restore@v4
      #   with:
      #     path: ./container-cache-in
      #     key: ${{ runner.os }}-
      #     restore-keys: |
      #       layers-${{ runner.os }}-${{ github.ref }}-${{ hashFiles('Dockerfile') }}
      #       layers-${{ runner.os }}-${{ github.ref }}
      #       layers-${{ runner.os }}

      - name: Set outputs
        id: vars
        run: |
          echo "tag_name=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT 
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            echo "tag_name=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT  
          fi

      # TODO combine all delivery jobs into a single action
      - name: Build container image
        uses: ./.github/actions/image-build
        with:
          path: .
          # TODO: the dockerfile path should be relative to the context path
          dockerfile: ./Dockerfile
          # TODO: add support for mixed case to workflow-engine (i.e. we should force container image tags to lowercase)
          image_tag: ghcr.io/cms-enterprise/batcave/workflow-engine:${{ steps.vars.outputs.tag_name }}
          # cache_from: ./container-cache-in
          # cache_to: ./container-cache-out
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Save image layer cache
      #   uses: actions/cache/save@v4
      #   with:
      #     path: ./container-cache-out
      #     key: layers-${{ runner.os }}-${{ github.ref }}-${{ hashFiles('Dockerfile') }}

      - name: Build podman container image
        uses: ./.github/actions/image-build
        with:
          path: .
          dockerfile: ./Dockerfile
          build_target: workflow-engine-podman
          workflow_engine_name: workflow-engine-podman-local
          image_tag: ghcr.io/cms-enterprise/batcave/workflow-engine:podman-${{ steps.vars.outputs.tag_name }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Scan container image
        uses: ./.github/actions/image-scan
        with:
          image_tag: ghcr.io/cms-enterprise/batcave/workflow-engine:${{ steps.vars.outputs.tag_name }}
          output_dir: ./artifacts
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Scan podman container image
        uses: ./.github/actions/image-scan
        with:
          image_tag: ghcr.io/cms-enterprise/batcave/workflow-engine:podman-${{ steps.vars.outputs.tag_name }}
          output_dir: ./artifacts
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      # TODO: this should be something workflow-engine does as apart of the delivery pipeline
      - name: Push image
        # TODO: in the future push based on protected git tags
        # if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        shell: bash
        run: docker push ghcr.io/cms-enterprise/batcave/workflow-engine:${{ steps.vars.outputs.tag_name }}

      - name: Push podman image
        shell: bash
        run: docker push ghcr.io/cms-enterprise/batcave/workflow-engine:podman-${{ steps.vars.outputs.tag_name }}

      - name: Archive image scan outputs
        uses: actions/upload-artifact@v4
        with:
          name: image-scan-results
          path: ./artifacts/*.json
          if-no-files-found: error
