name: Build workflow-engine
run-name: "Building workflow-engine Image: ${{ github.event.head_commit.message }}"
on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - main
jobs:
  workflow_engine:
    runs-on: ubuntu-latest
    name: Workflow Engine Code Scan + Image Delivery + Deployment Validation
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - name: Set outputs
        id: vars
        run: |
          export IMAGE_REPO=ghcr.io/cms-enterprise/batcave/workflow-engine
          echo "image_name=${IMAGE_REPO}:${GITHUB_SHA::8}" >> $GITHUB_OUTPUT 
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            echo "image_name=${IMAGE_REPO}:${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
          fi
          echo "VERSION=$(git describe --tags)" >> $GITHUB_ENV
          echo "GIT_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "GIT_DESCRIPTION=$(git log -1 --pretty=%B | head -n 1)" >> $GITHUB_ENV
      - name: Run Workflow Engine
        uses: cms-enterprise/batcave-workflow-engine-action@main
        # uses: ./.github/actions/workflow-engine
        with:
          build_dir: "."
          dockerfile: "Dockerfile"
          tag: ${{ steps.vars.outputs.image_name }}
          bundle_publish_enabled: false
          build_args: "VERSION=${{ env.VERSION }},GIT_COMMIT=${{ env.GIT_COMMIT }},GIT_DESCRIPTION=${{ env.GIT_DESCRIPTION }}"


