name: Build workflow-engine
run-name: "Building workflow-engine Image: ${{ github.event.head_commit.message }}"
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feat/*
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set outputs
        id: vars
        run: |
          echo "tag_name=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT 
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            echo "tag_name=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
          fi
          echo "VERSION=$(git describe --tags)" >> $GITHUB_OUTPUT
          echo "GIT_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "GIT_DESCRIPTION=$(git log -1 --pretty=%B | head -n 1)" >> $GITHUB_OUTPUT

      # TODO combine all delivery jobs into a single action
      - name: Build container image
        uses: ./.github/actions/image-build
        with:
          image_tag: ghcr.io/cms-enterprise/batcave/workflow-engine:${{ steps.vars.outputs.tag_name }}
          args: "VERSION=${{ steps.vars.outputs.VERSION }},GIT_COMMIT=${{ steps.vars.outputs.GIT_COMMIT }},GIT_DESCRIPTION=${{ steps.vars.outputs.GIT_DESCRIPTION }}"

      - name: Build podman container image
        uses: ./.github/actions/image-build
        with:
          target: workflow-engine-podman
          image_tag: ghcr.io/cms-enterprise/batcave/workflow-engine:podman-${{ steps.vars.outputs.tag_name }}
          args: "VERSION=${{ steps.vars.outputs.VERSION }},GIT_COMMIT=${{ steps.vars.outputs.GIT_COMMIT }},GIT_DESCRIPTION=${{ steps.vars.outputs.GIT_DESCRIPTION }}"

      - name: Scan container image
        uses: ./.github/actions/image-scan
        with:
          image_tag: ghcr.io/cms-enterprise/batcave/workflow-engine:${{ steps.vars.outputs.tag_name }}
          artifact_dir: ./artifacts

      - name: Scan podman container image
        uses: ./.github/actions/image-scan
        with:
          image_tag: ghcr.io/cms-enterprise/batcave/workflow-engine:podman-${{ steps.vars.outputs.tag_name }}
          artifact_dir: ./artifacts/podman

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish container image
        uses: ./.github/actions/image-publish
        with:
          image_tag: ghcr.io/cms-enterprise/batcave/workflow-engine:${{ steps.vars.outputs.tag_name }}
          bundle_tag: ghcr.io/cms-enterprise/batcave/workflow-engine:${{ steps.vars.outputs.tag_name }}-bundle

      - name: Publish podman container image
        uses: ./.github/actions/image-publish
        with:
          image_tag: ghcr.io/cms-enterprise/batcave/workflow-engine:podman-${{ steps.vars.outputs.tag_name }}
          bundle_tag: ghcr.io/cms-enterprise/batcave/workflow-engine:podman-${{ steps.vars.outputs.tag_name }}-bundle

      - name: job summary
        shell: bash
        run: |
          echo "## Workflow Engine Image Delivery Summary" >> $GITHUB_STEP_SUMMARY
          echo ":white_check_mark: Workflow Engine Image Build" >> $GITHUB_STEP_SUMMARY
          echo ":white_check_mark: Workflow Engine Image Scan" >> $GITHUB_STEP_SUMMARY
          echo ":white_check_mark: Image (Docker CLI): ghcr.io/cms-enterprise/batcave/workflow-engine:${{ steps.vars.outputs.tag_name }}" >> $GITHUB_STEP_SUMMARY
          echo ":white_check_mark: Image (Podman CLI): ghcr.io/cms-enterprise/batcave/workflow-engine:podman-${{ steps.vars.outputs.tag_name }}" >> $GITHUB_STEP_SUMMARY
      - name: Archive image scan outputs
        uses: actions/upload-artifact@v4
        with:
          name: image-scan-results
          path: |
            ./artifacts/**/*.json
            ./artifacts/**/*.txt
          if-no-files-found: error
